### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by ABadCandy** [llmapi-io/llmapi-lark#1]
![image](https://user-images.githubusercontent.com/19199003/230134263-2ac1d010-b588-4362-80a1-b5cff859a3d0.png)

浏览器打开127.0.0.1:12121时返回如图，

**Comment by llmapi** [comment]
![image](https://user-images.githubusercontent.com/126180784/230547570-37d487bb-7ba2-4563-ad76-7b28b651d92e.png)
server接受POST请求方法，是用于接收飞书发送过来的消息请求；目前不需要提供GET方法（比如浏览器访问地址会GET）。
目前启动的server是用于和飞书的机器人交互的
